# Generated by Django 3.1.2 on 2020-11-25 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('Navigation Bar', 'Nav'), ('Footer', 'Footer'), ('Full Page', 'FullPage')], max_length=20)),
                ('description', models.TextField()),
                ('htmlFile', models.FileField(upload_to='templates/html')),
                ('cssFile', models.FileField(upload_to='templates/css')),
                ('jsFile', models.FileField(blank=True, upload_to='templates/js')),
                ('noOfViews', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('Navigation Bar', 'Nav'), ('Footer', 'Footer'), ('Full Page', 'FullPage')], max_length=20)),
                ('description', models.TextField()),
                ('htmlFile', models.FileField(null=True, upload_to=home.models.get_html_path)),
                ('cssFile', models.FileField(blank=True, null=True, upload_to=home.models.get_css_path)),
                ('jsFile', models.FileField(blank=True, null=True, upload_to=home.models.get_js_path)),
                ('mediaFiles', models.FileField(blank=True, null=True, upload_to=home.models.get_file_path)),
                ('noOfViews', models.IntegerField(default=0, null=True)),
                ('colors', models.IntegerField(blank=True, default=0, null=True)),
                ('avgRating', models.IntegerField(blank=True, default=0, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[(1, 'Not Satisfactory'), (2, 'Satisfactory'), (3, 'Good'), (4, 'very Good'), (5, 'Excellent')], max_length=16)),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.template')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='profile_pics')),
                ('tag1', models.CharField(blank=True, max_length=100, null=True)),
                ('tag2', models.CharField(blank=True, max_length=100, null=True)),
                ('tag3', models.CharField(blank=True, max_length=100, null=True)),
                ('tag4', models.CharField(blank=True, max_length=100, null=True)),
                ('tag5', models.CharField(blank=True, max_length=100, null=True)),
                ('tag6', models.CharField(blank=True, max_length=100, null=True)),
                ('tag7', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.template')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
